@extends('layouts.app')

@section('title', 'Floor Plan')

@section('styles')
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link href="{{ asset('css/floorplan.css') }}" rel="stylesheet">
@endsection

@section('content')
  <div class="fp-wrapper">

    {{-- ── Controls Bar ── --}}
    <div class="fp-controls">
      <div class="fp-controls-group">
        <span class="fp-section-label">Building</span>
        <div class="building-tabs">
          <button class="building-tab active" data-building="A" onclick="selectBuilding('A')">Building A</button>
          <button class="building-tab"        data-building="B" onclick="selectBuilding('B')">Building B</button>
          <button class="building-tab"        data-building="C" onclick="selectBuilding('C')">Building C</button>
        </div>
      </div>

      <div class="fp-divider"></div>

      <div class="fp-controls-group">
        <span class="fp-section-label">Floor</span>
        <div class="floor-tabs" id="floorTabs">
          {{-- Generated by JS --}}
        </div>
      </div>

      <div class="fp-current" id="floorInfo">Building A &nbsp;·&nbsp; Floor 1</div>
    </div>

    {{-- ── Status Row ── --}}
    <div class="status-boxes" id="statusBoxes">
      <div class="status-box available">
        <div class="status-label"><i class="bi bi-check-circle"></i> Available</div>
        <span id="availableCount">0</span>
      </div>
      <div class="status-box reserved">
        <div class="status-label"><i class="bi bi-bookmark-check"></i> Reserved</div>
        <span id="reservedCount">0</span>
      </div>
      <div class="status-box contract">
        <div class="status-label"><i class="bi bi-file-earmark-text"></i> Contract</div>
        <span id="contractCount">0</span>
      </div>
      <div class="status-box installment">
        <div class="status-label"><i class="bi bi-credit-card"></i> Installment</div>
        <span id="installmentCount">0</span>
      </div>
      <div class="status-box transferred">
        <div class="status-label"><i class="bi bi-patch-check"></i> Transferred</div>
        <span id="transferredCount">0</span>
      </div>
    </div>

    {{-- ── Floor Plan ── --}}
    <div class="fp-main">
      <h2 id="contentTitle">Building A &nbsp;·&nbsp; Floor 1</h2>
      <div class="hotspot-container" id="hotspotContainer">
        {{-- Hotspots injected by JS --}}
      </div>
    </div>

  </div>

  {{-- ── Room Modal ── --}}
  <div class="modal" id="roomModal">
    <div class="modal-content room-modal-card">
      <button class="room-modal-close" onclick="closeModal()">&times;</button>
      <div id="roomDetails"></div>
    </div>
  </div>

  {{-- ── Quotation Visitor Modal (Bootstrap) ── --}}
  <div class="modal fade" id="fpQuotationModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Visitor Information</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <input type="hidden" id="fpQvSaleId">
          <input type="hidden" id="fpQvListingId">
          <input type="hidden" id="fpQvLanguage">
          <div class="mb-3">
            <label for="fpQvName" class="form-label">Name <span class="text-danger">*</span></label>
            <input type="text" class="form-control" id="fpQvName" placeholder="Enter visitor name">
            <div class="invalid-feedback" id="fpQvNameError"></div>
          </div>
          <div class="mb-3">
            <label for="fpQvPhone" class="form-label">Phone <span class="text-danger">*</span></label>
            <input type="text" class="form-control" id="fpQvPhone" placeholder="Enter phone number">
            <div class="invalid-feedback" id="fpQvPhoneError"></div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" id="fpQvSubmitBtn">
            <span class="spinner-border spinner-border-sm d-none me-1" id="fpQvSpinner"></span>
            Save & Preview
          </button>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
  <script src="{{ asset('js/floorplan.js') }}?v={{ filemtime(public_path('js/floorplan.js')) }}"></script>
@endsection
