@extends('layouts.app')

@section('title', 'Floor Plan')

@section('styles')
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link href="{{ asset('css/floorplan.css') }}" rel="stylesheet">
@endsection

@section('content')
  <div class="fp-wrapper">

    {{-- ── Controls Bar ── --}}
    <div class="fp-controls">
      <div class="fp-controls-group">
        <span class="fp-section-label">Building</span>
        <div class="building-tabs">
          <button class="building-tab active" data-building="A" onclick="selectBuilding('A')">Building A</button>
          <button class="building-tab"        data-building="B" onclick="selectBuilding('B')">Building B</button>
          <button class="building-tab"        data-building="C" onclick="selectBuilding('C')">Building C</button>
        </div>
      </div>

      <div class="fp-divider"></div>

      <div class="fp-controls-group">
        <span class="fp-section-label">Floor</span>
        <div class="floor-tabs" id="floorTabs">
          {{-- Generated by JS --}}
        </div>
      </div>

      <div class="fp-current" id="floorInfo">Building A &nbsp;·&nbsp; Floor 1</div>
    </div>

    {{-- ── Status Row ── --}}
    <div class="status-boxes" id="statusBoxes">
      <div class="status-box available">
        <div class="status-label"><i class="bi bi-check-circle"></i> Available</div>
        <span id="availableCount">0</span>
      </div>
      <div class="status-box reserved">
        <div class="status-label"><i class="bi bi-bookmark-check"></i> Reserved</div>
        <span id="reservedCount">0</span>
      </div>
      <div class="status-box contract">
        <div class="status-label"><i class="bi bi-file-earmark-text"></i> Contract</div>
        <span id="contractCount">0</span>
      </div>
      <div class="status-box installment">
        <div class="status-label"><i class="bi bi-credit-card"></i> Installment</div>
        <span id="installmentCount">0</span>
      </div>
      <div class="status-box transferred">
        <div class="status-label"><i class="bi bi-patch-check"></i> Transferred</div>
        <span id="transferredCount">0</span>
      </div>
    </div>

    {{-- ── Floor Plan ── --}}
    <div class="fp-main">
      <h2 id="contentTitle">Building A &nbsp;·&nbsp; Floor 1</h2>
      <div class="hotspot-container" id="hotspotContainer">
        {{-- Hotspots injected by JS --}}
      </div>
    </div>

  </div>

  {{-- ── Room Modal ── --}}
  <div class="modal" id="roomModal">
    <div class="modal-content">
      <h3 id="modalTitle">Room Details</h3>
      <div id="roomDetails"></div>
      <button onclick="closeModal()">Close</button>
    </div>
  </div>
@endsection

@section('scripts')
  <script src="{{ asset('js/floorplan.js') }}?v={{ filemtime(public_path('js/floorplan.js')) }}"></script>
@endsection
